FROM ubuntu:latest

# Esta parte no la necesitan realmente ustedes, pero igual, la voy a dejar comentada y lo escribo en español para su atención jaja
# Esencialmente esta parte sirve cuando están detrás de una proxy y necesitan especificar explícitamente
# los certificados para poderse conectar a internet con firmas de sus CAs.
# Es una configuración avanzada y no la necesitan realmente.

# # Set working directory
# WORKDIR /opt/certs

# # Update image and package lists
# RUN apt-get update \
#     && apt-get -y upgrade \
#     && apt-get clean

# USER root

# # Install common dependencies
# RUN apt-get update \
#     && apt-get -y install --no-install-recommends \
#     ca-certificates \
#     wget \
#     less \
#     tar 

# # Configure certificates
# COPY ../configs/certs/* /opt/certs
# RUN cp -a /opt/certs/* /usr/local/share/ca-certificates/
# RUN update-ca-certificates

# Install packages
RUN apt-get update && apt-get install -y \
    curl \
    bash-completion \
    openjdk-17-jdk \
    fontconfig \
    fonts-dejavu-core \
    software-properties-common \
    python3 \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install ANTLR
COPY antlr-4.13.1-complete.jar /usr/local/lib/antlr-4.13.1-complete.jar

COPY ./commands/antlr /usr/local/bin/antlr
RUN sed -i 's/\r$//' /usr/local/bin/antlr && chmod +x /usr/local/bin/antlr
COPY ./commands/antlr /usr/bin/antlr
RUN sed -i 's/\r$//' /usr/bin/antlr && chmod +x /usr/bin/antlr

COPY ./commands/grun /usr/local/bin/grun
RUN sed -i 's/\r$//' /usr/local/bin/grun && chmod +x /usr/local/bin/grun
COPY ./commands/grun /usr/bin/grun
RUN sed -i 's/\r$//' /usr/bin/grun && chmod +x /usr/bin/grun

COPY requirements.txt .
# Not production-intended, never do this, this is just a simple example
RUN pip install -r requirements.txt --break-system-packages 

# Set user
ARG USER=appuser
ARG UID=1001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"
USER ${UID}

WORKDIR /program
